
Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpr-build-comment[0m and container [32mstep-credential-initializer-8vkz2[0m
{"level":"warn","ts":1580733057.6680162,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1580733057.6690807,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpr-build-comment[0m and container [32mstep-working-dir-initializer-55vpm[0m
{"level":"warn","ts":1580733058.1303241,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580733058.1324644,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpr-build-comment[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpr-build-comment[0m and container [32mstep-create-dir-workspace-sqr2l[0m
{"level":"warn","ts":1580733064.2193978,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580733064.2225327,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpr-build-comment[0m and container [32mstep-git-source-seldonio-seldon-core-pr-1397-li-f5wbr[0m
{"level":"warn","ts":1580733064.523227,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1580733068.1975548,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/SeldonIO/seldon-core.git @ master in path /workspace/source"}

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpr-build-comment[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:2911d21cf3142cacf9c82cf40fc3c8e1e166e54f,1397:74edb31ffcaac17fc3007e5ba691a8fe9a88f854
DEBUG: ran git fetch --unshallow origin 74edb31ffcaac17fc3007e5ba691a8fe9a88f854: 2911d21cf3142cacf9c82cf40fc3c8e1e166e54f: in 
DEBUG: ran git checkout master in 
DEBUG: ran git reset --hard 2911d21cf3142cacf9c82cf40fc3c8e1e166e54f in 
DEBUG: ran clean --force -d . in 
DEBUG: ran git merge 74edb31ffcaac17fc3007e5ba691a8fe9a88f854 in 
Merged SHA 816ed7f7c267cb30fe5e048f78813e2977a951c7 with commit message 'Merge commit '74edb31ffcaac17fc3007e5ba691a8fe9a88f854'' into base branch master
Merged SHA 74edb31ffcaac17fc3007e5ba691a8fe9a88f854 with commit message 'Move pandas to requirements-dev' into base branch master
Merged SHA 65e5f01368b45d974bce7f451ff04a16c77081e5 with commit message 'Bump pandas from 0.25.3 to 1.0.0 in /python' into base branch master

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpr-build-comment[0m and container [32mstep-step2[0m
+++ dirname ./add-pr-build-comment
++ cd .
++ pwd
+ STARTUP_DIR=/workspace/source/ci
+ REPO_OWNER=SeldonIO
+ REPO_NAME=seldon-core
+ PULL_NUMBER=1397
+ BUILD_NUMBER=6
+ PIPELINE_CONTEXT=lint
++ cat
+++ date
+ COMMENT_MSG='Mon Feb  3 12:31:14 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1397/6.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1397 --build=6'
+ ** step pr comment --owner=SeldonIO --repository=seldon-core --pull-request=1397 '--comment=Mon Feb  3 12:31:14 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1397/6.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1397 --build=6'

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpr-build-comment[0m and container [32mstep-source-mkdir-seldonio-seldon-core-pr-1397-li-s9r2m[0m
{"level":"warn","ts":1580733076.396926,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580733076.4011536,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpr-build-comment[0m and container [32mstep-source-copy-seldonio-seldon-core-pr-1397-li-mlzqs[0m
{"level":"warn","ts":1580733076.6691608,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580733076.9970229,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r source/. /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpython-lint-task[0m and container [32mstep-credential-initializer-j675w[0m
{"level":"warn","ts":1580733081.243893,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1580733081.244726,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpython-lint-task[0m and container [32mstep-working-dir-initializer-rnch5[0m
{"level":"warn","ts":1580733082.291174,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580733082.293665,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpython-lint-task[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpython-lint-task[0m and container [32mstep-create-dir-workspace-58rz7[0m
{"level":"warn","ts":1580733085.3923674,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580733085.3947608,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpython-lint-task[0m and container [32mstep-source-copy-workspace-8pwhc[0m
{"level":"warn","ts":1580733085.6811476,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580733088.689335,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r /pvc/pr-build-comment/workspace/. /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1397-li-blx2b-6[0m stage [32mpython-lint-task[0m and container [32mstep-python-lint[0m
make: Entering directory '/workspace/source/python'
pip install black==19.3b0
Collecting black==19.3b0
  Downloading https://files.pythonhosted.org/packages/30/62/cf549544a5fe990bbaeca21e9c419501b2de7a701ab0afb377bc81676600/black-19.3b0-py36-none-any.whl (89kB)
Collecting appdirs
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting toml>=0.9.4
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting click>=6.5
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting attrs>=18.1.0
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Installing collected packages: appdirs, toml, click, attrs, black
Successfully installed appdirs-1.4.3 attrs-19.3.0 black-19.3b0 click-7.0 toml-0.10.0
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
black \
	--check ./ ../testing \
	--exclude "(testing/scripts/proto|seldon_core/proto/|.eggs|.tox)"
All done! ‚ú® üç∞ ‚ú®
53 files would be left unchanged.
make: Leaving directory '/workspace/source/python'
