
Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mpr-build-comment[0m and container [32mstep-credential-initializer-rgc5r[0m
{"level":"warn","ts":1593505429.7353418,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1593505429.735845,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mpr-build-comment[0m and container [32mstep-working-dir-initializer-b4ncw[0m
{"level":"warn","ts":1593505461.130622,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593505461.1330302,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mpr-build-comment[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mpr-build-comment[0m and container [32mstep-create-dir-workspace-z7wbj[0m
{"level":"warn","ts":1593505639.044245,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593505639.0457122,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mpr-build-comment[0m and container [32mstep-git-source-seldonio-seldon-core-pr-2029-pr-tlzcv[0m
{"level":"warn","ts":1593505639.2287934,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1593505653.4589233,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/SeldonIO/seldon-core.git @ master in path /workspace/source"}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mpr-build-comment[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:04ee26abd2767a65fb2a0b4fac94b2c7e2db4ead,2029:2af06b88fab97ca102b42dbbe8736877474494c1
DEBUG: ran git fetch --unshallow origin 2af06b88fab97ca102b42dbbe8736877474494c1: 04ee26abd2767a65fb2a0b4fac94b2c7e2db4ead: in 
DEBUG: ran git checkout master in 
DEBUG: ran git reset --hard 04ee26abd2767a65fb2a0b4fac94b2c7e2db4ead in 
DEBUG: ran clean --force -d . in 
DEBUG: ran git merge 2af06b88fab97ca102b42dbbe8736877474494c1 in 
Merged SHA 4016f8dc32bc3ba4cb9add6b9e841eec5ffd0a29 with commit message 'Merge commit '2af06b88fab97ca102b42dbbe8736877474494c1'' into base branch master
Merged SHA 2af06b88fab97ca102b42dbbe8736877474494c1 with commit message 'Update mypy requirement from <0.781 to <0.783 in /python' into base branch master

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mpr-build-comment[0m and container [32mstep-step2[0m
+++ dirname ./add-pr-build-comment
++ cd .
++ pwd
+ STARTUP_DIR=/workspace/source/ci
+ REPO_OWNER=SeldonIO
+ REPO_NAME=seldon-core
+ PULL_NUMBER=2029
+ BUILD_NUMBER=1
+ PIPELINE_CONTEXT=pr-build
++ cat
+++ date
+ COMMENT_MSG='Tue Jun 30 08:27:55 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2029/1.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-2029 --build=1'
+ ** step pr comment --owner=SeldonIO --repository=seldon-core --pull-request=2029 '--comment=Tue Jun 30 08:27:55 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2029/1.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-2029 --build=1'

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mpr-build-comment[0m and container [32mstep-source-mkdir-seldonio-seldon-core-pr-2029-pr-k7pk5[0m
{"level":"warn","ts":1593505681.1408725,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593505681.2017121,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mpr-build-comment[0m and container [32mstep-source-copy-seldonio-seldon-core-pr-2029-pr-9jt48[0m
{"level":"warn","ts":1593505681.7852705,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593505682.954192,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r source/. /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-engine[0m and container [32mstep-credential-initializer-7wqtq[0m
{"level":"warn","ts":1593506059.0742745,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1593506059.0748289,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-engine[0m and container [32mstep-working-dir-initializer-dj9vj[0m
{"level":"warn","ts":1593506078.1697564,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593506078.177235,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-engine[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-engine[0m and container [32mstep-create-dir-workspace-svhxp[0m
{"level":"warn","ts":1593506217.1164563,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593506217.11813,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-engine[0m and container [32mstep-source-copy-workspace-c2m2m[0m
{"level":"warn","ts":1593506217.3111181,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593506267.217866,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r /pvc/pr-build-comment/workspace/. /workspace/source\"; output "}
[31m
Pipeline failed on stage 'seldon-engine' : container 'step-source-copy-workspace-c2m2m'. The execution of the pipeline has stopped.[0m

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mtest-python[0m and container [32mstep-credential-initializer-nv4c7[0m
{"level":"warn","ts":1593506058.0480993,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1593506058.0486307,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mtest-python[0m and container [32mstep-working-dir-initializer-8fzr5[0m
{"level":"warn","ts":1593506080.2393818,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593506080.2794785,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mtest-python[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mtest-python[0m and container [32mstep-create-dir-workspace-dw256[0m
{"level":"warn","ts":1593506294.6220057,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593506294.623693,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}
[31m
Pipeline failed on stage 'test-python' : container 'step-create-dir-workspace-dw256'. The execution of the pipeline has stopped.[0m

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-executor[0m and container [32mstep-credential-initializer-v4trk[0m
{"level":"warn","ts":1593506059.010539,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1593506059.0125637,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-executor[0m and container [32mstep-working-dir-initializer-72rk5[0m
{"level":"warn","ts":1593506077.6056454,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593506077.6152363,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-executor[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-executor[0m and container [32mstep-create-dir-workspace-tlt96[0m
{"level":"warn","ts":1593506275.738872,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593506275.741386,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}
[31m
Pipeline failed on stage 'seldon-executor' : container 'step-create-dir-workspace-tlt96'. The execution of the pipeline has stopped.[0m

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-operator[0m and container [32mstep-credential-initializer-cbvqj[0m
{"level":"warn","ts":1593506058.8839183,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1593506058.892082,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-operator[0m and container [32mstep-working-dir-initializer-6clrb[0m
{"level":"warn","ts":1593506080.131246,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593506080.138796,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-operator[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-2029-pr-l68qf-1[0m stage [32mseldon-operator[0m and container [32mstep-create-dir-workspace-xtl49[0m
{"level":"warn","ts":1593506301.200435,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593506301.202398,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}
[31m
Pipeline failed on stage 'seldon-operator' : container 'step-create-dir-workspace-xtl49'. The execution of the pipeline has stopped.[0m
