
Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpr-build-comment[0m and container [32mstep-credential-initializer-d7dff[0m
{"level":"warn","ts":1581001063.183226,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581001063.1838274,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpr-build-comment[0m and container [32mstep-working-dir-initializer-z29d2[0m
{"level":"warn","ts":1581001064.5419424,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581001064.544033,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpr-build-comment[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpr-build-comment[0m and container [32mstep-create-dir-workspace-zk6jt[0m
{"level":"warn","ts":1581001070.6648848,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581001070.666854,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpr-build-comment[0m and container [32mstep-git-source-seldonio-seldon-core-pr-1365-li-ksrgd[0m
{"level":"warn","ts":1581001070.9450443,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581001074.429337,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/SeldonIO/seldon-core.git @ master in path /workspace/source"}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpr-build-comment[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:9e81a0067ca9fd7a18a41b32e37e5e0e68cb076c,1365:e5228fbb337eaad4fb2241763374bad142553447
DEBUG: ran git fetch --unshallow origin e5228fbb337eaad4fb2241763374bad142553447: 9e81a0067ca9fd7a18a41b32e37e5e0e68cb076c: in 
DEBUG: ran git checkout master in 
DEBUG: ran git reset --hard 9e81a0067ca9fd7a18a41b32e37e5e0e68cb076c in 
DEBUG: ran clean --force -d . in 
DEBUG: ran git merge e5228fbb337eaad4fb2241763374bad142553447 in 
Merged SHA 98f25c6a23f2c4b4756b2049f97717ec8ad08019 with commit message 'Merge commit 'e5228fbb337eaad4fb2241763374bad142553447'' into base branch master
Merged SHA e5228fbb337eaad4fb2241763374bad142553447 with commit message 'add test that checks model which route does not accept **kwargs' into base branch master
Merged SHA f20a522a68c20d6454bce3bfbf23e6df66abf94e with commit message 'allow route method to use metadata, closes #591' into base branch master

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpr-build-comment[0m and container [32mstep-step2[0m
+++ dirname ./add-pr-build-comment
++ cd .
++ pwd
+ STARTUP_DIR=/workspace/source/ci
+ REPO_OWNER=SeldonIO
+ REPO_NAME=seldon-core
+ PULL_NUMBER=1365
+ BUILD_NUMBER=23
+ PIPELINE_CONTEXT=lint
++ cat
+++ date
+ COMMENT_MSG='Thu Feb  6 14:58:01 UTC 2020
The logs for [lint] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1365/23.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1365 --build=23'
+ ** step pr comment --owner=SeldonIO --repository=seldon-core --pull-request=1365 '--comment=Thu Feb  6 14:58:01 UTC 2020
The logs for [lint] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1365/23.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1365 --build=23'

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpr-build-comment[0m and container [32mstep-source-mkdir-seldonio-seldon-core-pr-1365-li-w5vg5[0m
{"level":"warn","ts":1581001084.7206876,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581001084.725913,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpr-build-comment[0m and container [32mstep-source-copy-seldonio-seldon-core-pr-1365-li-cm9v8[0m
{"level":"warn","ts":1581001084.9895108,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581001085.3316343,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r source/. /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpython-lint-task[0m and container [32mstep-credential-initializer-knzbm[0m
{"level":"warn","ts":1581001088.229585,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581001088.2300925,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpython-lint-task[0m and container [32mstep-working-dir-initializer-6vc8x[0m
{"level":"warn","ts":1581001089.2466655,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581001089.2488184,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpython-lint-task[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpython-lint-task[0m and container [32mstep-create-dir-workspace-zmxj7[0m
{"level":"warn","ts":1581001093.4483457,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581001093.451294,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpython-lint-task[0m and container [32mstep-source-copy-workspace-mbhhh[0m
{"level":"warn","ts":1581001093.7195837,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581001094.1394145,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r /pvc/pr-build-comment/workspace/. /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-r96g8-23[0m stage [32mpython-lint-task[0m and container [32mstep-python-lint[0m
make: Entering directory '/workspace/source/python'
pip install black==19.3b0
Collecting black==19.3b0
  Downloading https://files.pythonhosted.org/packages/30/62/cf549544a5fe990bbaeca21e9c419501b2de7a701ab0afb377bc81676600/black-19.3b0-py36-none-any.whl (89kB)
Collecting attrs>=18.1.0
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting click>=6.5
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting appdirs
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting toml>=0.9.4
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Installing collected packages: attrs, click, appdirs, toml, black
Successfully installed appdirs-1.4.3 attrs-19.3.0 black-19.3b0 click-7.0 toml-0.10.0
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
black \
	--check ./ ../testing \
	--exclude "(testing/scripts/proto|seldon_core/proto/|.eggs|.tox)"
All done! ‚ú® üç∞ ‚ú®
54 files would be left unchanged.
make: Leaving directory '/workspace/source/python'
