
Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpr-build-comment[0m and container [32mstep-credential-initializer-s62mt[0m
{"level":"warn","ts":1580136152.2766309,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1580136152.2771113,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpr-build-comment[0m and container [32mstep-working-dir-initializer-s7p2j[0m
{"level":"warn","ts":1580136153.2629123,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580136153.2650428,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpr-build-comment[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpr-build-comment[0m and container [32mstep-create-dir-workspace-z6kwn[0m
{"level":"warn","ts":1580136159.5677104,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580136159.5706697,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpr-build-comment[0m and container [32mstep-git-source-seldonio-seldon-core-pr-1365-li-dl7ls[0m
{"level":"warn","ts":1580136159.8489268,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1580136163.228472,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/SeldonIO/seldon-core.git @ master in path /workspace/source"}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpr-build-comment[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:f3343e3a5fb3ff619430722d96ed0f53d88dc595,1365:230b3c0c2c5fb685857dec4b244e3ff5a57c7fc6
DEBUG: ran git fetch --unshallow origin 230b3c0c2c5fb685857dec4b244e3ff5a57c7fc6: f3343e3a5fb3ff619430722d96ed0f53d88dc595: in 
DEBUG: ran git checkout master in 
DEBUG: ran git reset --hard f3343e3a5fb3ff619430722d96ed0f53d88dc595 in 
DEBUG: ran clean --force -d . in 
DEBUG: ran git merge 230b3c0c2c5fb685857dec4b244e3ff5a57c7fc6 in 
Merged SHA b4be522d253cb4f5635a24517698f364da1179fe with commit message 'Merge commit '230b3c0c2c5fb685857dec4b244e3ff5a57c7fc6'' into base branch master
Merged SHA 230b3c0c2c5fb685857dec4b244e3ff5a57c7fc6 with commit message 'add test that checks model which route does not accept **kwargs' into base branch master
Merged SHA 53b5c180a3334fb5a92bbdb5ea9276ea82ed80a0 with commit message 'allow route method to use metadata, closes #591' into base branch master

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpr-build-comment[0m and container [32mstep-step2[0m
+++ dirname ./add-pr-build-comment
++ cd .
++ pwd
+ STARTUP_DIR=/workspace/source/ci
+ REPO_OWNER=SeldonIO
+ REPO_NAME=seldon-core
+ PULL_NUMBER=1365
+ BUILD_NUMBER=9
+ PIPELINE_CONTEXT=lint
++ cat
+++ date
+ COMMENT_MSG='Mon Jan 27 14:42:50 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1365/9.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1365 --build=9'
+ ** step pr comment --owner=SeldonIO --repository=seldon-core --pull-request=1365 '--comment=Mon Jan 27 14:42:50 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1365/9.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1365 --build=9'

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpr-build-comment[0m and container [32mstep-source-mkdir-seldonio-seldon-core-pr-1365-li-47tsd[0m
{"level":"warn","ts":1580136173.766395,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580136173.787799,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpr-build-comment[0m and container [32mstep-source-copy-seldonio-seldon-core-pr-1365-li-fwstx[0m
{"level":"warn","ts":1580136174.0609207,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580136174.3594806,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r source/. /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpython-lint-task[0m and container [32mstep-credential-initializer-wlfqq[0m
{"level":"warn","ts":1580136178.9313257,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1580136178.9320292,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpython-lint-task[0m and container [32mstep-working-dir-initializer-87t8q[0m
{"level":"warn","ts":1580136179.958429,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580136179.9603446,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpython-lint-task[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpython-lint-task[0m and container [32mstep-create-dir-workspace-h2p5w[0m
{"level":"warn","ts":1580136188.3249576,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580136188.3277657,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpython-lint-task[0m and container [32mstep-source-copy-workspace-q572k[0m
{"level":"warn","ts":1580136188.6268854,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580136188.9186337,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r /pvc/pr-build-comment/workspace/. /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1365-li-2lrx7-9[0m stage [32mpython-lint-task[0m and container [32mstep-python-lint[0m
make: Entering directory '/workspace/source/python'
pip install black==19.3b0
Collecting black==19.3b0
  Downloading https://files.pythonhosted.org/packages/30/62/cf549544a5fe990bbaeca21e9c419501b2de7a701ab0afb377bc81676600/black-19.3b0-py36-none-any.whl (89kB)
Collecting click>=6.5
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting appdirs
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting attrs>=18.1.0
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting toml>=0.9.4
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Installing collected packages: click, appdirs, attrs, toml, black
Successfully installed appdirs-1.4.3 attrs-19.3.0 black-19.3b0 click-7.0 toml-0.10.0
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
black \
	--check ./ ../testing \
	--exclude "(testing/scripts/proto|seldon_core/proto/|.eggs|.tox)"
All done! ‚ú® üç∞ ‚ú®
53 files would be left unchanged.
make: Leaving directory '/workspace/source/python'
