
Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpr-build-comment[0m and container [32mstep-credential-initializer-7g4kh[0m
{"level":"warn","ts":1581505689.549563,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581505689.550011,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpr-build-comment[0m and container [32mstep-working-dir-initializer-mn82k[0m
{"level":"warn","ts":1581505690.8675737,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581505690.8690357,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpr-build-comment[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpr-build-comment[0m and container [32mstep-create-dir-workspace-cqtmz[0m
{"level":"warn","ts":1581505696.957759,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581505696.9590778,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpr-build-comment[0m and container [32mstep-git-source-seldonio-seldon-core-pr-1424-li-q2p4k[0m
{"level":"warn","ts":1581505697.1953018,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581505700.3040075,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/SeldonIO/seldon-core.git @ master in path /workspace/source"}

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpr-build-comment[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:50cd020a11804fb2cb6aa9c96d011f2a5cb2ce85,1424:83dc13781bac71621460250921dbdce4eb2b08e7
DEBUG: ran git fetch --unshallow origin 83dc13781bac71621460250921dbdce4eb2b08e7: 50cd020a11804fb2cb6aa9c96d011f2a5cb2ce85: in 
DEBUG: ran git checkout master in 
DEBUG: ran git reset --hard 50cd020a11804fb2cb6aa9c96d011f2a5cb2ce85 in 
DEBUG: ran clean --force -d . in 
DEBUG: ran git merge 83dc13781bac71621460250921dbdce4eb2b08e7 in 
Merged SHA 60d22037c8440171e9b7586684930994775bec42 with commit message 'Merge commit '83dc13781bac71621460250921dbdce4eb2b08e7'' into base branch master
Merged SHA 83dc13781bac71621460250921dbdce4eb2b08e7 with commit message 'enable logging in python/tests from INFO level' into base branch master
Merged SHA 277a73159fc5456591e64bb2188c6ac9d255c037 with commit message 'Replace print with logging.info in python/tests. Closes #1372' into base branch master

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpr-build-comment[0m and container [32mstep-step2[0m
+++ dirname ./add-pr-build-comment
++ cd .
++ pwd
+ STARTUP_DIR=/workspace/source/ci
+ REPO_OWNER=SeldonIO
+ REPO_NAME=seldon-core
+ PULL_NUMBER=1424
+ BUILD_NUMBER=13
+ PIPELINE_CONTEXT=lint
++ cat
+++ date
+ COMMENT_MSG='Wed Feb 12 11:08:26 UTC 2020
The logs for [lint] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/13.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1424 --build=13'
+ ** step pr comment --owner=SeldonIO --repository=seldon-core --pull-request=1424 '--comment=Wed Feb 12 11:08:26 UTC 2020
The logs for [lint] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/13.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1424 --build=13'

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpr-build-comment[0m and container [32mstep-source-mkdir-seldonio-seldon-core-pr-1424-li-zqlxk[0m
{"level":"warn","ts":1581505708.9663794,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581505708.9693735,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpr-build-comment[0m and container [32mstep-source-copy-seldonio-seldon-core-pr-1424-li-6xj5q[0m
{"level":"warn","ts":1581505709.2037706,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581505709.4599617,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r source/. /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpython-lint-task[0m and container [32mstep-credential-initializer-kzzmj[0m
{"level":"warn","ts":1581505713.6121087,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581505713.6126165,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpython-lint-task[0m and container [32mstep-working-dir-initializer-xqg2w[0m
{"level":"warn","ts":1581505715.587546,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581505715.589093,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpython-lint-task[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpython-lint-task[0m and container [32mstep-create-dir-workspace-2zmlg[0m
{"level":"warn","ts":1581505720.0196614,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581505720.0210974,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpython-lint-task[0m and container [32mstep-source-copy-workspace-ld7g6[0m
{"level":"warn","ts":1581505720.277889,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581505724.1064389,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r /pvc/pr-build-comment/workspace/. /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1424-li-zv4vl-13[0m stage [32mpython-lint-task[0m and container [32mstep-python-lint[0m
make: Entering directory '/workspace/source/python'
pip install black==19.3b0
Collecting black==19.3b0
  Downloading black-19.3b0-py36-none-any.whl (89 kB)
Collecting click>=6.5
  Downloading Click-7.0-py2.py3-none-any.whl (81 kB)
Collecting toml>=0.9.4
  Downloading toml-0.10.0-py2.py3-none-any.whl (25 kB)
Collecting appdirs
  Downloading appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
Collecting attrs>=18.1.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Installing collected packages: click, toml, appdirs, attrs, black
Successfully installed appdirs-1.4.3 attrs-19.3.0 black-19.3b0 click-7.0 toml-0.10.0
black \
	--check ./ ../testing \
	--exclude "(testing/scripts/proto|seldon_core/proto/|.eggs|.tox)"
would reformat /workspace/source/python/tests/conftest.py
All done! ðŸ’¥ ðŸ’” ðŸ’¥
1 file would be reformatted, 54 files would be left unchanged.
make: Leaving directory '/workspace/source/python'
make: *** [Makefile:104: run_linter_check] Error 1
[31m
Pipeline failed on stage 'python-lint-task' : container 'step-python-lint'. The execution of the pipeline has stopped.[0m
