
Showing logs for build [32mmeta-seldonio-seldon-core-pr-19-qj2nq-6[0m stage [32mmeta-pipeline[0m and container [32mstep-credential-initializer-d7zrt[0m
{"level":"warn","ts":1592904533.4324625,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1592904533.43304,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mmeta-seldonio-seldon-core-pr-19-qj2nq-6[0m stage [32mmeta-pipeline[0m and container [32mstep-working-dir-initializer-gtxrm[0m
{"level":"warn","ts":1592904534.8033702,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1592904534.9242582,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mmeta-seldonio-seldon-core-pr-19-qj2nq-6[0m stage [32mmeta-pipeline[0m and container [32mstep-place-tools[0m

Showing logs for build [32mmeta-seldonio-seldon-core-pr-19-qj2nq-6[0m stage [32mmeta-pipeline[0m and container [32mstep-git-source-meta-seldonio-seldon-core-pr-19-jcvq9[0m
{"level":"warn","ts":1592904542.9022,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1592904548.6785157,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/SeldonIO/seldon-core.git @ 51e9153a3cb25ac4dad352d3c5dde9787c547b83 in path /workspace/source"}

Showing logs for build [32mmeta-seldonio-seldon-core-pr-19-qj2nq-6[0m stage [32mmeta-pipeline[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:51e9153a3cb25ac4dad352d3c5dde9787c547b83,1999:d3905fd94bd74c62280ae9651b90068d3e3bc3c4
DEBUG: ran git fetch --unshallow origin d3905fd94bd74c62280ae9651b90068d3e3bc3c4: 51e9153a3cb25ac4dad352d3c5dde9787c547b83: in 
DEBUG: ran git checkout master in 
DEBUG: ran git reset --hard 51e9153a3cb25ac4dad352d3c5dde9787c547b83 in 
DEBUG: ran clean --force -d . in 
error: error during merge: merging d3905fd94bd74c62280ae9651b90068d3e3bc3c4 into master: git output: Auto-merging executor/go.sum
Auto-merging executor/go.mod
CONFLICT (content): Merge conflict in executor/go.mod
Automatic merge failed; fix conflicts and then commit the result.: failed to run 'git merge d3905fd94bd74c62280ae9651b90068d3e3bc3c4' command in directory '', output: 'Auto-merging executor/go.sum
Auto-merging executor/go.mod
CONFLICT (content): Merge conflict in executor/go.mod
Automatic merge failed; fix conflicts and then commit the result.'
[31m
Pipeline failed on stage 'meta-pipeline' : container 'step-git-merge'. The execution of the pipeline has stopped.[0m
