
Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpr-build-comment[0m and container [32mstep-credential-initializer-jd6cz[0m
{"level":"warn","ts":1580490451.3866348,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1580490451.3870852,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpr-build-comment[0m and container [32mstep-working-dir-initializer-hkt6t[0m
{"level":"warn","ts":1580490451.842885,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580490451.844353,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpr-build-comment[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpr-build-comment[0m and container [32mstep-create-dir-workspace-pf6s5[0m
{"level":"warn","ts":1580490457.994097,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580490457.9968474,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpr-build-comment[0m and container [32mstep-git-source-seldonio-seldon-core-pr-1383-li-kfg4w[0m
{"level":"warn","ts":1580490458.299783,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1580490462.031386,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/SeldonIO/seldon-core.git @ master in path /workspace/source"}

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpr-build-comment[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:7bf6653953b9c9766e8e2c5dbdc882bdc997c3f4,1383:66fd4a0d536e799d2bb6a1fe68874962cf9c29a4
DEBUG: ran git fetch --unshallow origin 66fd4a0d536e799d2bb6a1fe68874962cf9c29a4: 7bf6653953b9c9766e8e2c5dbdc882bdc997c3f4: in 
DEBUG: ran git checkout master in 
DEBUG: ran git reset --hard 7bf6653953b9c9766e8e2c5dbdc882bdc997c3f4 in 
DEBUG: ran clean --force -d . in 
DEBUG: ran git merge 66fd4a0d536e799d2bb6a1fe68874962cf9c29a4 in 
Merged SHA 1e85aae60ef2f6691e1adb332cdd80a6f86df642 with commit message 'Merge commit '66fd4a0d536e799d2bb6a1fe68874962cf9c29a4'' into base branch master
Merged SHA 66fd4a0d536e799d2bb6a1fe68874962cf9c29a4 with commit message 'Update ambassador docs' into base branch master
Merged SHA 903eaf15bc283d66cbaaab9e618f72d1c5018d53 with commit message 'Update amabassador retries and restructure tests for Ambassador' into base branch master

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpr-build-comment[0m and container [32mstep-step2[0m
+++ dirname ./add-pr-build-comment
++ cd .
++ pwd
+ STARTUP_DIR=/workspace/source/ci
+ REPO_OWNER=SeldonIO
+ REPO_NAME=seldon-core
+ PULL_NUMBER=1383
+ BUILD_NUMBER=6
+ PIPELINE_CONTEXT=lint
++ cat
+++ date
+ COMMENT_MSG='Fri Jan 31 17:07:47 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/6.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1383 --build=6'
+ ** step pr comment --owner=SeldonIO --repository=seldon-core --pull-request=1383 '--comment=Fri Jan 31 17:07:47 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/6.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1383 --build=6'

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpr-build-comment[0m and container [32mstep-source-mkdir-seldonio-seldon-core-pr-1383-li-slcpd[0m
{"level":"warn","ts":1580490470.202172,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580490470.205584,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpr-build-comment[0m and container [32mstep-source-copy-seldonio-seldon-core-pr-1383-li-kjhtz[0m
{"level":"warn","ts":1580490470.4858074,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580490470.782976,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r source/. /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpython-lint-task[0m and container [32mstep-credential-initializer-nf65h[0m
{"level":"warn","ts":1580490486.112714,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1580490486.1132438,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpython-lint-task[0m and container [32mstep-working-dir-initializer-qpk5s[0m
{"level":"warn","ts":1580490486.6190734,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580490486.6244614,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpython-lint-task[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpython-lint-task[0m and container [32mstep-create-dir-workspace-v6ct9[0m
{"level":"warn","ts":1580490492.2890472,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580490492.291417,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpython-lint-task[0m and container [32mstep-source-copy-workspace-rhjf8[0m
{"level":"warn","ts":1580490492.7121124,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580490495.088991,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r /pvc/pr-build-comment/workspace/. /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1383-li-t79cg-6[0m stage [32mpython-lint-task[0m and container [32mstep-python-lint[0m
make: Entering directory '/workspace/source/python'
pip install black==19.3b0
Collecting black==19.3b0
  Downloading https://files.pythonhosted.org/packages/30/62/cf549544a5fe990bbaeca21e9c419501b2de7a701ab0afb377bc81676600/black-19.3b0-py36-none-any.whl (89kB)
Collecting attrs>=18.1.0
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting appdirs
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting toml>=0.9.4
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting click>=6.5
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Installing collected packages: attrs, appdirs, toml, click, black
Successfully installed appdirs-1.4.3 attrs-19.3.0 black-19.3b0 click-7.0 toml-0.10.0
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
black \
	--check ./ ../testing \
	--exclude "(testing/scripts/proto|seldon_core/proto/|.eggs|.tox)"
All done! ‚ú® üç∞ ‚ú®
53 files would be left unchanged.
make: Leaving directory '/workspace/source/python'
